### ISSUE TITLE
SECRET_KEY AND DJANGO ver.

### ISSUE THREAD

**Issue by pixelography** [Kshatriya770/Grocery-Store#5]
The secret_key is missing, throwing  undefinedValueError..it can be fixed by putting up a secret_key in base.py 

which version of django are you using? (showing errors that are related to django.utils.six which is dropped by django in the latest version)

couldn't run server because of these errors :(

**Comment by Kshatriya770** [comment]
Did you follow the steps?

What version of python you're using?

Or

Try starting a virtual environment in Visual Studio code..

Use Django 2.2 for safe side..

**Comment by sourav517** [comment]
I'm also suffering from same problem, please help
